version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy:
    machine:
      enabled: true

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install virtualenv
            virtualenv -p python3 venv
            source venv/bin/activate
            pip install -r requirements.txt

      # Deployment commands
      - run:
          name: Start Gunicorn Server
          command: |
            . venv/bin/activate
            gunicorn --bind 0.0.0.0:8000 run:app

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
